before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - deploy
   
build:
  tags:
     - ece651
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh


deploy:
  tags:
    - ece651
  stage: deploy
  script: ./scripts/redeploy.sh  
