/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651_g10.server;

import java.io.IOException;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        //TODO: Test remote connection.
        RuleChecker moveRuleChecker = new TerritoryExistChecker(new PlayerSelfOrderChecker(new SelfTerritoryChecker(new ConnectedTerritoryChecker(new SufficientUnitChecker(null)))));
        RuleChecker attackRuleChecker = new TerritoryExistChecker(new PlayerSelfOrderChecker(new EnemyTerritoryChecker(new AdjacentTerritoryChecker(new SufficientUnitChecker(null)))));
        GameMapFactory factory = new V1GameMapFactory(new PseudoNumberGenerator());
        //GameMapFactory factory = new FixedGameMapFactory();
        Server server = new Server(12345, 3, 12, 4, factory, moveRuleChecker, attackRuleChecker, new V1OrderProcessor());
        //server.acceptConnections();
        server.run();
    }
}
