/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651_g10.server;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, InterruptedException {
        PasswordGenerator passwordGenerator = new V2ServerPasswordGenerator();
        Server server = new Server(12345, passwordGenerator);
        server.run();
    }
}
