package edu.duke.ece651_g10.server;

/**
 * Create the isolated random number generator so that we can mock this and test the related GameMapFactory.
 * Maintained By Guancheng Fu.
 */
public interface RandomNumberGenerator {
    /**
     * Returns the next pseudorandom, uniformly distributed int value from this random number generator's sequence.
     * @return The next number generated by the generator.
     */
    public int nextInt();

    /**
     * Returns the next number in the range [0, bound)
     * @param bound The right bound (exclusive)
     * @return The generated random number.
     */
    public int nextInt(int bound);
}
